### ISSUE TITLE
xed: Please bring back the dark mode switch

### ISSUE THREAD

**Issue by axel358** [linuxmint/mint21.2-beta#1]
https://github.com/linuxmint/xed/issues/587

**Comment by anaximeno** [comment]
If you hit **prefer dark** in theme settings (the settings section inside the theme setting module) it stays in dark mode, but this comes with the downside of libadwaita apps being dark by default also.

**Comment by JosephMcc** [comment]
I don't think we need the dark mode switch back but Xed should use the dark theme when "Let Applications decide" is chosen. Even other text editors like Sublime Text use the dark theme with this setting.

> If you hit prefer dark in theme settings (the settings section inside the theme setting module) it stays in dark mode, but this comes with the downside of libadwaita apps being dark by default also.

Just to clear something up. No default apps in Mint use Libadwaita. That library is Gtk4 only. The apps in question use libhandy which is basically it's precursor and for Gtk3. A lot of default Mint apps use it and it's unfortunate that you are stuck with them all dark just to get the text editor dark.

**Comment by axel358** [comment]
I understand that some(maybe most) people might want to use xed for just basic text editing so while xed being dark by default woukd resolve my issue since i mostly using for code editing im afraid it might create a similar issue for them. Also even when my eyes cant stand the light theme ive met a fee people(well actually just one) that can't stand dark theme for coding. So maybe Xed being light by default but still providing a way to switch it to dark without affecting the rest of the system cpuld be a good aproach for everyone no matter what they preffer

**Comment by clefebvre** [comment]
Text editor has always been light by default. You can't really compare with sublime. I understand you might want to use Xed for coding, but for most people, it's the txt mime handler, nothing more. It's what we ship with by default, it really should stay light by default imo.

**Comment by axel358** [comment]
GTE is even more basic than xed and still offers dark mode while being light by default. I don't understand the motivation behind removing the option

**Comment by clefebvre** [comment]
Brought back in 3.4.2.

**Comment by axel358** [comment]
@clefebvre, thank you :)

**Comment by axel358** [comment]
Maybe it would be a good idea if Xed could still honor the "Prefer dark" and "Prefer light" global settings and only show/apply it's internal preference when "Let applications decide" is active or when running on a desktop where the portal is not available ?
