### ISSUE TITLE
cinnamon: Tooltips stop working

### ISSUE THREAD

**Issue by Elliot4444** [linuxmint/mint21.2-beta#11]
Tooltips stop working in panel completely.

Steps to reproduce:

- Turn off "Group windows by application" in the Grouped windows list applet.
![grafik](https://github.com/linuxmint/mint21.2-beta/assets/117015561/ec82462b-199b-4919-92ee-021c907208a8)
- Open two windows of one application, e.g. Firefox.
- Close one window by middleclick on the application button on the panel.
- No more toolstips anywhere until restarting Cinnamon.

**Comment by clefebvre** [comment]
Fixed in master.
