### ISSUE TITLE
mintmenu: All applications icon is branded

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21.2-beta#12]
In mate's mintmenu, when using the Yaru or Breeze icons, the theme logo is displayed, as shown in the image below:
![Screenshot at 2023-06-21 18-45-28](https://github.com/linuxmint/mint21.2-beta/assets/59381215/6890f272-6468-4983-9a3e-b15d5619f59f)
![Screenshot at 2023-06-21 18-46-05](https://github.com/linuxmint/mint21.2-beta/assets/59381215/cbceb278-e338-4996-acfa-ff097f3c6d99)
It is only possible to do the same in the cinnamon menu that uses this icon for all themes:
![cinnamon-all-applications-symbolic](https://github.com/linuxmint/mint21.2-beta/assets/59381215/b424f9a8-3b7e-490e-aed0-259543d5e0fc)

**Comment by mtwebster** [comment]
Those are those themes' 'start-here-symbolic' icons, so technically this is working as intended :)

We use the 'cinnamon-all-applications' icon in Cinnamon.

**Comment by Initu-Castilhos** [comment]
> I know, but in my opinion it's better to have a single icon for all themes.  In MATE, for example, it is strange to use the Breeze icon and the Plasma and Yaru logos appear with the Ubuntu logo in Linux Mint.

**Comment by Initu-Castilhos** [comment]
👍🏼
