### ISSUE TITLE
Adds colored applications-multimedia icon in Adwaita

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21.2-beta#13]
The applications-mutimedia icon in Adwaita is symbolic since Linux Mint 19, I know it's from GNOME. Example as shown in the image below:
![227735707-291596b2-385e-469c-8387-ba1d5e2a7928](https://github.com/linuxmint/mint21.2-beta/assets/59381215/5085ceef-a70c-4651-8064-b0d032376060)

Expected behaviour

The solution is to copy the gnome icon that is located in categories and paste it in Adwaita in the legacy folder in sizes: 16,22,24,32 and 48. Example as shown in the image below:
![227735934-7d99941e-ce1a-4021-9b74-e3b6475f0ce5](https://github.com/linuxmint/mint21.2-beta/assets/59381215/5ceb48e3-2d46-40df-97a4-01f34759047d)

**Comment by clefebvre** [comment]
This should be reported to Adwaita directly. They're part of GTK, they should work in any desktop really, whether GNOME uses this category or not.
