### ISSUE TITLE
[Cinnamon] mintwelcome - "Traditional" panel preset is missing

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.2-beta#14]
In mintwelcome, the panel preset for "Tradional" is missing.

[video.webm](https://github.com/linuxmint/mint21.2-beta/assets/11896003/b77fb616-0375-435e-bd8b-c667e5f90ecf)

I can't help but reminded of my "tin-foil hat conspiracy theory" from back in the 21.1 beta where I theorized that the end-goal for future versions was to in fact remove the "Traditional" panel preset:
- https://github.com/linuxmint/mint21.1-beta/issues/45

(by the way, speaking of beta versions, considering the long "readme" for this temporary 21.2 git emphasizing that you're only interested in bugs that didn't exist on 21.1, I suppose my list of bugs that I've gathered over the last 3-ish months should wait until non-beta 21.2 before I retest and/or report them? The idea is that using a live ISO makes for much easier reproducibility and demonstration, not to mention a much easier way to check if a given bug is or isn't still present in the newest version of Mint, but there's only a period of maybe a month or two where a given versions live ISO is even applicable to the current version of Mint)

**Comment by clefebvre** [comment]
Well there's no conspiracy here. It's always been the plan to add this temporarily and then to remove it.

See https://github.com/linuxmint/mint21.1-beta/issues/45#issuecomment-1346965276.

As we change defaults we try to accommodate for people who don't want to switch, but we change defaults all the time.
