### ISSUE TITLE
mintupdate: kernel window not fully localized

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint21.2-beta#15]
I have Polish language set on my OS and the kernel manager is using a mix of English and Polish. I remember it working normally before.
![kernels](https://github.com/linuxmint/mint21.2-beta/assets/84787215/45b27966-feee-4e34-a1f8-6b498469d0a0)

**Comment by clefebvre** [comment]
I can reproduce it in French.

**Comment by clefebvre** [comment]
Fixed in 6.0.2
