### ISSUE TITLE
[MATE] - Caja 'Change Colour' does not honour theme icon set

### ISSUE THREAD

**Issue by PurpleZeroHero** [linuxmint/mint21.2-beta#17]
Steps to reproduce:

1. pick a legacy theme icon set (**mint-y-legacy-dark** for example)
2. right click on folder and select change colour to red

The icons are different

![Screenshot at 2023-06-22 05-03-12](https://github.com/linuxmint/mint21.2-beta/assets/137369759/5d0ab0b1-4f28-4634-807a-13ff0862bc04)

In 21.1 the 'caja-folder-color-switcher.py' had KNOWN_THEMES section which allowed the script to try pick the same icon set.
This is missing in the 21.2 version, however there does seem to be a change where it is looking at JSON files in **/usr/share/folder-color-colors.d/** to determine which icon set to use, but this does not seem to be working.

**Comment by clefebvre** [comment]
Please pick Mint-L instead.

Mint-Y-Legacy no longer exists. It's been renamed Mint-L.

Mint-L should come with proper folder-color-switcher support.

**Comment by PurpleZeroHero** [comment]
Just tested again

Set theme to 'Mint-L-Dark' and changed the folder colour, the icon is incorrectly set to the 'Mint-Y' coloured icon instead of the appropriate coloured 'Mint-L' icon

![foldericon](https://github.com/linuxmint/mint21.2-beta/assets/137369759/6c1a0501-3f28-48ea-9c28-cc1a8cbb70c8)
