### ISSUE TITLE
[MATE] - Caja icon differences between 21.1 & 21.2

### ISSUE THREAD

**Issue by PurpleZeroHero** [linuxmint/mint21.2-beta#18]
This appears to be across all Mint Y and Mint L themes (light /dark and legacy ones)

**Toolbar**

![1-toolbar](https://github.com/linuxmint/mint21.2-beta/assets/137369759/aa5345d2-56ff-4884-8f39-3666a81f61a5)

**Location bar**

![2-location](https://github.com/linuxmint/mint21.2-beta/assets/137369759/00dedd4c-ad8b-4c8f-95c7-a1df070bad2b)

**Search Bar**

![3-search](https://github.com/linuxmint/mint21.2-beta/assets/137369759/851231d9-3ba9-48e1-8269-024d633e5f92)

**Contextual Menu**

![4-ctx](https://github.com/linuxmint/mint21.2-beta/assets/137369759/67544100-594b-42ee-b106-3df742ac23cb)

**Comment by clefebvre** [comment]
This is by design. We removed all mono icons. It makes Caja work better with a variety of GTK themes than it did before. It also makes it more ugly though, but that's subjective.

For a complete fix, Caja needs to switch to symbolic icons.

**Comment by PurpleZeroHero** [comment]
Adding my subjective opinion, it looks terrible :)
