### ISSUE TITLE
pix: Missing translations

### ISSUE THREAD

**Issue by mahtiankka** [linuxmint/mint21.2-beta#19]
The language pack in Mint launchpad net is 744 lines long. I was surprised when I couldn't find e.g. "About Pix" or many others under Settings.

I made the test by naming the gthumb language package -> pix.mo. Surprise yes, it worked. It has 1100 lines and I suspect that the launchpad pix file is missing lines.

I would be happy if you have time to fix it.

** If I make changes to the gthumb.po file and upload it to launchpad? Is it possible? Am I making a big mistake?

Thank you

*** If I can still make a wish? Because Drawing is Mint's default program. Would it be possible to make it translate to launchpad as well. It is version 0.8.5 and it is partly in Finnish and partly in English. I've been translating the program since the beginning, but it's never been quite right on Linux Mint releases. I can't use the version 1.0.0 translation because it doesn't work in the old version.

The OS Cinnamon 21.2 beta

![Kuva1](https://github.com/linuxmint/mint21.2-beta/assets/48694735/b3d56d80-67bd-42d6-ab75-818082f45078)

![Kuva2](https://github.com/linuxmint/mint21.2-beta/assets/48694735/3b63dbee-3f71-40b0-8952-a3565adafbc9)

**Comment by clefebvre** [comment]
Ah thanks, the pot file wasn't picking up .ui files. This adds 360 msgids into Launchpad :)

For drawing, no, but I'll have a look to see if we can backport 1.0.2.
