### ISSUE TITLE
cinnamon menu: categories blink when there is a window playing a video behind the menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#21]
steps to follow:

1- play a video with the browser [Firefox].
2- open the cinnamon menu and navigate through the categories section.

In this case Youtube in theater mode [it also happens with Twitch]:

[blinking menu.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/bd225bc3-4c6d-4753-b7f9-28ff97c047e9)

In my case it happens when playing the video with the window maximized [1366x768 screen] and only one screen connected.
By deactivating in the menu settings the options 'show category icons' or 'show favorites and session buttons' the bug disappears.

PS. Seems to be this [bug](https://github.com/linuxmint/cinnamon/issues/10212) or something similar.

**Comment by haggen88** [comment]
I have noticed that the problem seems to be with the edges of the video players, at least the flicker seems to be aligned to them:

[video borders.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/511e33ff-8cf3-473a-aa8b-ba5a9cc1ccb4)

**EDIT:** It does not only happen with the browser with maximized window, apparently it depends on the border of the player to match the border of the categories section of the menu:

[border.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/c139e396-fe0a-46f7-9765-c1ab4ddf4129)

Only happens with Firefox [as deb or flatpak].

Hardware info [nothing from nvidia is installed]
> Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Hewlett-Packard driver: i915 v: kernel
    ports: active: eDP-1 empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:0a16
  Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]
    vendor: Hewlett-Packard driver: nouveau v: kernel pcie: speed: 2.5 GT/s lanes: 4 bus-ID: 09:00.0
    chip-ID: 10de:1140
  Device-3: Chicony HP Webcam type: USB driver: uvcvideo bus-ID: 1-1.5:4 chip-ID: 04f2:b493
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96
  Monitor-1: eDP-1 model: Chi Mei Innolux res: 1366x768 dpi: 112 diag: 355mm (14")
  OpenGL: renderer: Mesa Intel HD Graphics 4400 (HSW GT2) v: 4.6 Mesa 22.2.5 direct render: Yes

**Comment by anaximeno** [comment]
Here's another situation where something similar happens (I am not sure if it is the same case though):

https://github.com/linuxmint/mint21.2-beta/assets/63073056/6783550a-7557-404b-82d6-f996fed8d021

There I am using the click effects of the Cinnamon Eyes applet. To show the click effect the applet loads an image and adds it to the uiGroup (Main.uiGroup) to perform the animation.

**Comment by mtwebster** [comment]
I can reproduce the video issue but not cinnamon eyes - that works fine for me (not blocking out the menu highlight). It's definitely related to the older bug you mentioned.

**Comment by clefebvre** [comment]
Not a blocker but we'll have a look at it post-release. Added to 21.3 roadmap.
