### ISSUE TITLE
UEFI Secure boot: Verification Failed (0x1A) Security Violation

### ISSUE THREAD

**Issue by samliddicott** [linuxmint/mint21.2-beta#24]
if Ubuntu 22.04.2 has been installed on a machine with secureboot, then this ISO image will not boot unless secureboot is first disabled. secureboot can be enabled once this beta is installed and the ISO will still boot. Until ubuntu 22.04.2 is installed, and then it won't boot the ISO.

This is always re-producible.

Steps to re-produce:

I refer to these installation steps
1. boot $INSTALLER ISO over USB
2. install system without network connectivity
3. reboot system
4. with network connectivity get all updates
5. reboot

Use those steps like this
1. disable secure boot 
2. Repeat steps above for INSTALLER=linuxmint-21.2-beta
3. enable secure boot
4. Observe that linuxmint beta still boots, and so does ISO over USB
5. Repeat steps above to install Ubuntu 22.04.2 (without disabling secure boot)
6. Observe that ubuntu 22.04.2 still boots, and so does ubuntu ISO over USB
7. **Observe that linux mint beta ISO will no longer boot**. The blue mok error screen says: "Verification failed: (0x1A) Security Violation"

How come ubuntu 22.04.2 ISO will always boot but more recent mint 21.2 beta will not unless secureboot is disabled?

**Comment by clefebvre** [comment]
Hi Sam,

It's a known issue. It's in the release notes. This release (and all past releases) no longer support SecureBoot. SHIM signatures have been updated by Microsoft and Canonical. We need to address this issue by changing the way we produce ISO images and this is planned post 21.2 release.
