### ISSUE TITLE
cinnamon: The menu applet is too tall by default

### ISSUE THREAD

**Issue by axel358** [linuxmint/mint21.2-beta#26]
I don't know if this is related to the sizing issue but seems like the default menu height is 650 which in my screen takes almost 90% of it. I also noticed it on the screenshot in the release announcement,  there's almost 30% of blank space at the bottom

**Comment by haggen88** [comment]
At first I thought the larger menu was to promote the use of the new feature [ability to resize with the mouse], now that I see it is larger than the standard which I think is 550px.
