### ISSUE TITLE
Unmount icon is too close to the scrollbar in nemo

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint21.2-beta#28]
This seems like a regression since in the current stable 21.1 there is more space between the unmount icon and the scroll bar:

### Current Stable: 21.1
![Screenshot from 2023-06-23 01-01-32](https://github.com/linuxmint/mint21.2-beta/assets/63073056/2547bd93-f862-4a2f-b9e0-bc780579ef67)

### Beta: 21.2
![Screenshot from 2023-06-23 02-10-27](https://github.com/linuxmint/mint21.2-beta/assets/63073056/57c43d07-ebe5-4055-99e7-86fdc3834d62)

**Comment by kacperpaczos** [comment]
Yes, I can see the difference, but I have an updated version, and I don't have this bug. I don't know if this bug was present before the update.
![image](https://github.com/linuxmint/mint21.2-beta/assets/23406555/997b608d-011d-4826-be4b-cb2dfcd025e2)

**Comment by mtwebster** [comment]
I get the too-close version on 21.0, .1 and .2.

I'll see what I can do - it's tricky because the sidebar is arranged in columns - I can't move the eject button without affecting how wide the location/device name column is, but it's unusable if you have enough items there to need a scrollbar.
