### ISSUE TITLE
Gesture log flood in .xsession-errors

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint21.2-beta#29]
This may not directly influence the user's flow, but it still might be a problem when debugging the system.

![Screenshot from 2023-06-23 02-23-50](https://github.com/linuxmint/mint21.2-beta/assets/63073056/b17864cc-e759-4481-93bd-8cfc63cdbaf3)

**Comment by mtwebster** [comment]
Those are indicating something's wrong, so I think something's wrong (there are no gesture 'starts', only updates and ends) - can you provide more information?

Are you using gestures when this occurs? Just using a touchpad normally? What scenario is this occurring in? Is it a specific gesture type causing this?

**Comment by anaximeno** [comment]
From what I've noticed, this mostly happens when there are no actions set to the gesture I'm performing. As if I performed a four finger pinch action but this specific action is disabled.

I've tested only in the touchpad.
