### ISSUE TITLE
mintinstall: after installing an app, the size appears as 'disk space freed' instead of 'disk space used'.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#3]
![2 installed](https://github.com/linuxmint/mint21.2-beta/assets/68134588/81f2a9af-b74a-46f0-9189-cb0db8266480)

PS. Software Manager looks great!

**Comment by mtwebster** [comment]
This is because after an app is installed, it updates to reflect  what would happen if you *uninstalled* it. It's always been this way I believe.

**Comment by haggen88** [comment]
IMHO it sounds more useful to know how much space the app occupies.

BTW same issue #[343](https://github.com/linuxmint/mintinstall/issues/343)

**Comment by LinuxOnTheDesktop** [comment]
> This is because after an app is installed, it updates to reflect what would happen if you uninstalled it.

But the window does not say that X MB would be freed (upon removal). It says 'X MB freed' - as  if the space has been gained _already_ - which it has not. What _has_ happened is that the space has been _used_. So surely the text should read: 'X MB used' or - better perhaps - just 'X MB'.

**Comment by clefebvre** [comment]
'X MB' sounds good to me.
