### ISSUE TITLE
Some buttons are not visible in LibreOffice when using the dark mode

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint21.2-beta#30]
This isn't a new issue, if I'm not wrong, it's been happening since Mint 21, and could easily be solved by installing one of the LibreOffice styles that support both light and dark modes, along with the default installation of LibreOffice.

![Screenshot from 2023-06-23 02-17-10](https://github.com/linuxmint/mint21.2-beta/assets/63073056/1400dbee-dbf4-46b9-9dae-1c854160816c)

### Example: LibreOffice Elementary Style: `libreoffice-style-elementary`

![Screenshot from 2023-06-23 02-00-18](https://github.com/linuxmint/mint21.2-beta/assets/63073056/688c06b7-c439-4c8a-9acf-1e1e134d6394)

For more reference see this issue https://github.com/linuxmint/linuxmint/issues/544

**Comment by kacperpaczos** [comment]
It's an old bug of LibreOffice:
https://bugs.documentfoundation.org/show_bug.cgi?id=127138
They continuously repair and slowly fix this problem in the newest version. If you need this to work better on your computer, you should use:
https://launchpad.net/~libreoffice/+archive/ubuntu/ppa

The only way to fix it in LM is to make a script to manually change the configuration of LibreOffice. I believe that Ubuntu made this hotfix available in the GNOME center in their version because it works better than LM.

![image](https://github.com/linuxmint/mint21.2-beta/assets/23406555/2ac53755-9c20-4357-8bca-9e8610e6f154)

**Comment by clefebvre** [comment]
Although visible libreoffice-style-elementary isn't great in dark themes, and it doesn't look as nice as LO's default Colibre in light themes.

We'll add libreoffice-style-breeze to the default package selection. This won't make it work fully out of the box, but at least when people go in LO's preferences, Breeze (dark) will be in the list, already installed and ready to be chosen.

**Comment by Isolator70** [comment]
The icon set of choice would be "Colibre_dark". Surprisingly this set is available [here](https://github.com/rizmut/libreoffice-style-colibre), but not not available in LibreOffice.
Beside the "Colibre_dark"  - which looks crisp sharp there is also "Colibre_dark_svg" which on all my machines (no scaling of the UI) looks blurred.
![2023-06-29_21-27](https://github.com/linuxmint/mint21.2-beta/assets/35434137/046745d6-83b9-4656-ba27-fd8bce0a7239)

**Comment by Isolator70** [comment]
> ....could easily be solved by installing...
> 

> ### Example: LibreOffice Elementary Style: `libreoffice-style-elementary`
> 
> ![Screenshot from 2023-06-23 02-00-18](https://user-images.githubusercontent.com/63073056/248142770-688c06b7-c439-4c8a-9acf-1e1e134d6394.png)
> 
> For more reference see this issue [linuxmint/linuxmint#544](https://github.com/linuxmint/linuxmint/issues/544)

Sorry, but 

1. the mentioned Elementary Style is also not usable in Dark mode - some icons are hard to see:

![2023-06-29_21-49](https://github.com/linuxmint/mint21.2-beta/assets/35434137/3214eb25-3146-4a87-92f2-067616e642b3)
 
2. Who shall "easily" do the installation of the icon set? The end user? This is not acceptable, as LM offers the dark mode, but one of the main applications is not usable in this way. An Icon set suitable for dark mode has to be shipped as a standard and ideally switch automatically according to the systems mode
