### ISSUE TITLE
Firefox isn't starting

### ISSUE THREAD

**Issue by dudelll** [linuxmint/mint21.2-beta#31]
"Close Firefox" msg appears saying it is already running but not responding. Reproducible after reboot. Chromium / Brave start normally. Independent of Wired / Wireless. Process status is sleeping, second process starting with running, but switches to sleeping after the error msg appears. Not responding msg at restart.

Installed on mini PC BMAX 1 Plus with added wireless driver.

Attached 
- system info
- sw list
- various screenshots
- 
- [Firefox.tar.gz](https://github.com/linuxmint/mint21.2-beta/files/11844585/Firefox.tar.gz)

**Comment by dudelll** [comment]
After a couple of restarts and ending / killing of the firefox-bin process in the System Monitor, Firefox is now starting and running with 2 or 3 instances instead of 1 or 2 as before.

![Screenshot from 2023-06-23 14-50-07](https://github.com/linuxmint/mint21.2-beta/assets/137478956/4abd5c69-e02b-4642-b5a7-d4ac4726557a)
![Screenshot from 2023-06-23 14-53-28](https://github.com/linuxmint/mint21.2-beta/assets/137478956/a5b8dc73-1ddd-4d47-9715-b0d9c7bc07ab)

**Comment by anaximeno** [comment]
I had this same issue after upgrading Firefox to the last version, to solve this I had to kill that firefox-bin process that was running in the background and open Firefox from the terminal using:
```bash
firefox --browser
```
After that it would always open without any problem, as usual.
This happened while I was using 21.1 so I am not sure if it is a regression, but if more  people had this problem it might be good to reallocate this issue to a more appropriate repository.

**Comment by dudelll** [comment]
On my second install it didn't happen again; but the difference was that I used a shared home folder / partition of the previously installed Debian 12 (Firefox ESR).

**Comment by mtwebster** [comment]
I have this happen every so often (maybe 3 times in the past year), but it's not isolated to Mint as far as I can see if I do a search.

It seems to involve Firefox not exiting cleanly and removing its profile locks - 
https://unix.stackexchange.com/questions/67166/why-does-firefox-refuse-to-die-despite-killing-it-with-pkill-9

I'm not saying this is the specific reason for you, but just that this isn't really an isolated thing.
