### ISSUE TITLE
Display / Monitor Scale > 100% makes system / mouse / video lagging

### ISSUE THREAD

**Issue by dudelll** [linuxmint/mint21.2-beta#33]
If Monitor Scale is increased, the system gets slower, especially the mouse movement is lagging, worse in combination with video playing. Video itself is also lagging. Set back to default setting of 100% and the effect is gone. Also reproduced on min 21.1.

System:
  Kernel: 5.15.0-75-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.8.2
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: AMI model: Intel serial: <superuser required> UEFI: American Megatrends
    v: 1.2_217 date: 10/13/2022
CPU:
  Info: dual core model: Intel Celeron N3350 bits: 64 type: MCP arch: Goldmont rev: 9 cache:
    L1: 112 KiB L2: 2 MiB
  Speed (MHz): avg: 1014 high: 1089 min/max: 800/2400 cores: 1: 1089 2: 940 bogomips: 4377
  Flags: ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel HD Graphics 500 driver: i915 v: kernel ports: active: HDMI-A-1 empty: DP-1
    bus-ID: 00:02.0 chip-ID: 8086:5a85
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-1 mapped: HDMI-A-1 model: MS3663 res: 1920x1080 dpi: 85
  OpenGL: renderer: Mesa Intel HD Graphics 500 (APL 2) v: 4.6 Mesa 22.2.5-0ubuntu0.1~22.04.3
    direct render: Yes
Audio:
  Device-1: Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
    driver: sof-audio-pci-intel-apl bus-ID: 00:0e.0 chip-ID: 8086:5a98
  Device-2: Harman JBL Pebbles type: USB driver: hid-generic,snd-usb-audio,usbhid bus-ID: 1-4:2
    chip-ID: 05fc:0231
  Sound Server-1: ALSA v: k5.15.0-75-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 02:00.0 chip-ID: 10ec:8168
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter driver: rtl8821ce
    v: v5.5.2.1_35598.20191029 pcie: speed: 2.5 GT/s lanes: 1 port: d000 bus-ID: 05:00.0
    chip-ID: 10ec:c821
  IF: wlp5s0 state: down mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8 bus-ID: 1-7:4
    chip-ID: 0bda:c821
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: f098
Drives:
  Local Storage: total: 238.47 GiB used: 12.07 GiB (5.1%)
  ID-1: /dev/sda vendor: Hikvision model: HS-SSD-E100N 256G size: 238.47 GiB speed: 3.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 19.06 GiB used: 12.06 GiB (63.3%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 126 MiB used: 11.8 MiB (9.4%) fs: vfat dev: /dev/sda1
Swap:
  Alert: No swap data was found.
Sensors:
  System Temperatures: cpu: 67.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: apt: 2233
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirror.kku.ac.th/linuxmint-packages victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/protonvpn-stable.list
    1: deb [arch="all", signed-by=/usr/share/keyrings/protonvpn-stable-archive-keyring.gpg] https: //repo.protonvpn.com/debian stable main
  Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https: //updates.signal.org/desktop/apt xenial main
Info:
  Processes: 229 Uptime: 29m Memory: 5.63 GiB used: 2.37 GiB (42.1%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/12 Client: Cinnamon v: 5.8.2 inxi: 3.3.13

**Comment by JosephMcc** [comment]
If you are talking about the fractional scaling, this is unfortunately a limitation of it. I know some people use it and it works for them but on my own machines I've never really found it usable. That's why it's marked experimental. The way it works is putting a lot of additional demand on your system.

**Comment by dudelll** [comment]
Maybe it should be deactivated by default if it is experimental (I didn't know, I just saw the config dlg where it states that it is experimental).

**Comment by clefebvre** [comment]
We'll disable it by default, this was an oversight.
