### ISSUE TITLE
cinnamon: Changing styles should affect the Dark mode preference

### ISSUE THREAD

**Issue by axel358** [linuxmint/mint21.2-beta#35]
Shouldn't changing styles between Mixed, Dark and Light also set Dark mode to Let applications decide, Prefer dark, Prefer light respectively?

**Comment by mdevansh06** [comment]
Sounds good but see #16

**Comment by clefebvre** [comment]
Ideally it would, in practice though, it would prevent people from getting the outcome they want or even troubleshooting light/dark issues.

**Comment by Lurux** [comment]
@clefebvre, may I suggest this should be handled like any other theme component currently tied to Cinnamon styles ?

In other words, choosing a style would set the option accordingly, but users would still be able to go into the advanced settings and change it individually, just like any of the other theme components.

I think this would be the behavior that most people expect, while still allowing users to tinker or troubleshoot dark mode if needed.

**Comment by mdevansh06** [comment]
@Lurux, this is what i expected the styles to do.
i expected dark to set prefer-dark, light to set prefer-light and mixed to default(let app decide)

**Comment by axel358** [comment]
@clefebvre we're not talking about removing the advanced preference just changing it along with the styles. In my opinion when a user chooses Dark style they expect all apps to be dark, including those that wont be affected by changing the gtk theme

**Comment by axel358** [comment]
Seems like there is a PR for this https://github.com/linuxmint/cinnamon/pull/11706

**Comment by Qronikarz** [comment]
> in practice though, it would prevent people from getting the outcome they want or even troubleshooting light/dark issues.

That was the only reason? I thought you meant something important here https://github.com/linuxmint/mint21.2-beta/issues/4#issuecomment-1601051025
How's that different from allowing to change mouse icon set? It's also set when you select a theme in simplified window.

**Comment by Lurux** [comment]
> Seems like there is a PR for this

Indeed, this seems to do what we're describing here. I don't want to spam the team to much, but I may ping them on this PR if they don't acknowledge it - they may have missed it because of the beta rush.

@MrQuerter, please make sure to stay polite - maybe we're missing something here, or maybe the team just didn't think about it.

Anyways, I hope we get an acknowledgement soon, even if the issue doesn't end up being resolved. Would be nice to know someone looked at the solution...

**Comment by Qronikarz** [comment]
@Lurux I was polite. I just asked a question and then provided example of how it works currently. I do hope we're missing something here, but it wasn't indicated as such in the explanation above.

**Comment by Lurux** [comment]
Oh sorry, I felt like your first line was a bit condescending, just wanted to make sure the maintainers don't feel like we're harassing them over this issue 🙂
