### ISSUE TITLE
Translation error in theme settings.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21.2-beta#37]
The translation of Personalize is wrong. The correct translation is "Personalizado" for Brazilian Portuguese.
![Captura de tela de 2023-06-23 15-34-14](https://github.com/linuxmint/mint21.2-beta/assets/59381215/22f5155f-6da8-4cde-a4cd-57a5a9f39822)

**Comment by fredcw** [comment]
Translations are done on Launchpad. See https://linuxmint-translation-guide.readthedocs.io/en/latest/translate.html

**Comment by hugok79** [comment]
Contact: Alberlan Lopes <alberlan@gmail.com>

https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/pt_BR/1362/+translate

**Comment by clefebvre** [comment]
Updated in LP. Will get synced prior to Stable.
