### ISSUE TITLE
Not able to add downloaded applets to panel

### ISSUE THREAD

**Issue by mdevansh06** [linuxmint/mint21.2-beta#38]
**Description**: In cinnamon edition, downloaded applets do not appear in panel, even after adding them through system settings.
**Steps to reproduce**: Download any applet from applets in system settings and try to add it to panel. It does not appear in the panel or in panel edit mode.
_I am not running live iso, but upgraded my 21.1 vera to 21.2 victoria by editing the apt sources in official-repositories.list_

**Comment by anaximeno** [comment]
I didn't had this problem while testing, can you give more information?

There's a file called `.xsessions-errors` in your home directory, try to add those applets then send it.

Also give the name of the applets you are not being able to add to the panel, as it could be that they are not compatible with the new version.

**Comment by rcalixte** [comment]
@mdevansh06 Can you see if resetting things helps? (Right-click on any panel -> Troubleshoot -> "Restore all settings to default")

**Comment by mdevansh06** [comment]
The applets now add properly, without me doing anything special. Maybe the applets were updated to support cinnamon 5.8.
btw, the applets were cinnamenu and cinnVIIstarkmenu
