### ISSUE TITLE
Wrong icon for external SSD drive

### ISSUE THREAD

**Issue by MiZoG99** [linuxmint/mint21.2-beta#39]
Wrong icon in address bar and side bar in Nemo for an SSD storage drive mounted via USB inside a third-party enclosure.
It is ugreen case for 2.5' disks

<blockquote class="imgur-embed-pub" lang="en" data-id="PwuKmb6"><a href="https://imgur.com/PwuKmb6">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

lsusb detects it as:

`Bus 002 Device 004: ID 174c:1153 ASMedia Technology Inc. ASM1153 SATA 3Gb/s bridge`

inxi shows only information about the drive enclosed not the "sata-bridge":
```
 ID-2: /dev/sdb maj-min: 8:16 type: USB vendor: Silicon Power
    model: SPCC Solid State Disk size: 476.94 GiB block-size: physical: 512 B
    logical: 512 B type: SSD serial: <filter> scheme: MBR
```
[Full system specs](https://termbin.com/nva4f)

Different filesystem (ext4, exFAT, ntfs) changes nothing.
Drive is currently empty. There is no windows-styled autorun.ini or anything like that.
**Same case with a 2.5 HDD this time appears with the correct (USB external drive) icon!**

**Comment by Reno-Sifana** [comment]
> Wrong icon in address bar and side bar in Nemo for an SSD storage drive mounted via USB inside a third-party enclosure. It is ugreen case for 2.5' disks
> 
> > [View post on imgur.com](https://imgur.com/PwuKmb6)
> 
> <script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
> 
> lsusb detects it as:
> 
> `Bus 002 Device 004: ID 174c:1153 ASMedia Technology Inc. ASM1153 SATA 3Gb/s bridge`
> 
> inxi shows only information about the drive enclosed not the "sata-bridge":
> 
> ```
>  ID-2: /dev/sdb maj-min: 8:16 type: USB vendor: Silicon Power
>     model: SPCC Solid State Disk size: 476.94 GiB block-size: physical: 512 B
>     logical: 512 B type: SSD serial: <filter> scheme: MBR
> ```
> 
> [Full system specs](https://termbin.com/nva4f)
> 
> Different filesystem (ext4, exFAT, ntfs) changes nothing. Drive is currently empty. There is no windows-styled autorun.ini or anything like that. **Same case with a 2.5 HDD this time appears with the correct (USB external drive) icon!**

@mtwebster What do you think about this bug? it's seems need fix them before the Linux Mint 21.2 was launched to General Availability / RTM.

**Comment by mtwebster** [comment]
Can you run:
```
nemo --quit
NEMO_DEBUG_DEVICE_ICONS=1 nemo
```
and paste the output.

**Comment by MiZoG99** [comment]
`Message: 18:30:01.304: mount 512 GB Volume: icon name 'drive-harddisk-solidstate-usb-symbolic' is being used`

**Comment by clefebvre** [comment]
Fallback should work: 

![image](https://github.com/linuxmint/mint21.2-beta/assets/1138515/29ac49ee-2d72-4d82-aaa9-0a17d9caf154)

**Comment by clefebvre** [comment]
What icon theme are you using @MiZoG99 ?

Your trash icon is different than the one from Mint-Y.

**Comment by carlosmintfan** [comment]
@clefebvre Hey, what's that icon tester application you are using? (Is it a tool of yours? Is it something I can download too if I want?)

**Comment by MiZoG99** [comment]
> What icon theme are you using @MiZoG99 ?
> 
> Your trash icon is different than the one from Mint-Y.

Just the default theme. But I did "browse" several themes for a while to see if problem persists. Was under the impression that I had reverted to default when the screenshot was taken.

**Comment by mtwebster** [comment]
@carlosmintfan https://github.com/linuxmint/mint-dev-tools/blob/master/usr/bin/mint-test-icon-lookup

**Comment by mtwebster** [comment]
closing: https://github.com/linuxmint/nemo/commit/06ff292e65216bf4ddf237e55981f9751fb13b4c

There should never be an 'invalid' icon for devices in the sidebar.
