### ISSUE TITLE
Dark/Light mode switch doesn't affect some Flatpak programs

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint21.2-beta#4]
https://github.com/linuxmint/cinnamon/issues/10934
From this it seems that newest Mint should allow setting dark mode for Flatpak apps, but some are unaffected:

Tested that work:
+ Geany
+ GtkHash
+ Pinta
+ ungoogled-chromium

Tested that maybe work (just title bar changes):
+ Audacious
+ GIMP
+ Heroic Games Launcher
+ LossLessCut
+ PeaZip
+ Upscayl
+ VLC
+ Youtube Downloader Plus

Tested that don't work:
+ Bottles
+ Czkawka
+ Flatseal
+ Footage
+ Inkscape
+ LibreWolf
+ OnlyOffice

How I tested
Open selected program. Open the theme switcher program. Select Mint-Y style with green accent and click on dark theme button and light theme button while looking at the program that you have opened before to see if it changes.

**Comment by anaximeno** [comment]
Does it work if you close and reopen the program?

**Comment by Qronikarz** [comment]
No it doesn't. In fact even rebooting OS doesn't help with that since I have dark mode enabled nearly permanently and don't use light mode.

**Comment by clefebvre** [comment]
It only works with apps which support the XDG dark mode specification.

Are you using a light theme or a dark theme? Do you expect your Flatpaks to be dark?

**Comment by Qronikarz** [comment]
Bottles should support XDG specifications.
There's more info there:
https://github.com/bottlesdevs/Bottles/issues/1758
https://github.com/bottlesdevs/Bottles/issues/1990

This is what I use and I do expect Flatpaks to be dark.
![thme](https://github.com/linuxmint/mint21.2-beta/assets/84787215/d5e6092a-2050-4f14-b5f1-00d0168ac56b)

**Comment by clefebvre** [comment]
What is your dark mode setting set to?

**Comment by clefebvre** [comment]
It looks like Bottles actively tries not to get themed :)

It seems to be using Adwaita no matter what. Looking at their code they even go as far as unsetting GTK_THEME from the environment. You can't expect this app to theme properly.

**Comment by Qronikarz** [comment]
Ok I found it. Now only Czkawka and OnlyOffice don't work and it's probably their fault.

Still, if we have a redesigned theme window maybe it would be a good idea to have the new simplified mode setting tied to the actual settings?

Like, clicking on dark mode button on the window that I posted above before should also change the setting here:
![sett](https://github.com/linuxmint/mint21.2-beta/assets/84787215/b0c5abd5-8c60-49e0-aa67-aaa800048fa5)
Right now you can make an reverse of the problem:
![onlyflatpakdark](https://github.com/linuxmint/mint21.2-beta/assets/84787215/c6f2628f-a78a-4c7e-984e-d7bd48f957d1)

**Comment by clefebvre** [comment]
No, it's a completely different thing. We wanted to do what you said initially but found out you needed to be able to switch xdg dark mode independently.

**Comment by Qronikarz** [comment]
I feel like it's gonna get reported much in the future, but if you say that it needed to be not linked together then probably there's good reason for that.
