### ISSUE TITLE
Several apps take long time to start

### ISSUE THREAD

**Issue by SantiBurgos1089** [linuxmint/mint21.2-beta#40]
SCENARIO:
There are several apps that take a long time to start after clicking on them, I thought that the issue was with my laptop (and I'm using both refurbished ones) or my SSD, but it seems to be particular to Cinnamon, which is what I'm using currently, so far the list of apps I have detected are the following:

* Firefox (See also issue #31 , I guess it can be related to that as well but I'm not sure either)
* System monitor
* gnome-calculator
* dconf-editor

At least on Archlinux, it seems that that issue lies within several Gnome apps (the former 3 are the version found on Gnome, which all of them rely on GTK4/libadwaita), I'm not sure if this is only outside of Linux Mint, other apps (like for example gparted, several cinnamon-settings windows, libreoffice, lightdm-settings) take their time based on resources or open almost instantly

EXPECTED RESULT:

Unless that the PC resources are limited, the apps should not take that long to load and open

ACTUAL RESULT:

Several apps take a long time to load (almost 1 minute), at least on my PC I have enough resources (I don't intend to sound arrogant with this, my apologies before hand if it does) and I don't have much apps open (well, maybe some chromium-based browsers which may consume, but even with few windows open, the problem persists)

![Info](https://github.com/linuxmint/mint21.2-beta/assets/137421608/8c9d3a3f-8bbb-4813-913d-2b88a922a79c)

![Monitor](https://github.com/linuxmint/mint21.2-beta/assets/137421608/2e52b5cf-b1e2-459e-83ec-813480c7b205)

**Comment by JosephMcc** [comment]
If this is a Cinnamon issue it should really be reported against Cinnamon. The tracker is for the Linux Mint Beta which this doesn't seem to have anything to do with. The issue template there also asks for more relevant info since you aren't using Mint.

**Comment by mtwebster** [comment]
if you have xdg-desktop-portal-gnome installed, try removing it.

ref:
https://github.com/linuxmint/xdg-desktop-portal-xapp/commit/86a1cb27eff487f6245319e850c1c560a8ba33ed
https://github.com/flatpak/xdg-desktop-portal/issues/1032

**Comment by SantiBurgos1089** [comment]
Thank @mtwebster that did the trick (I had no idea how I ended up installing that x-d-p-gnome package but removing it worked)

**Comment by hugok79** [comment]
In Manjaro the solution was to remove **xdg-desktop-portal-gnome** and install **xdg-desktop-portal-gtk**
