### ISSUE TITLE
Wrong dependencies in the package?

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/mint21.2-beta#42]
![image](https://github.com/linuxmint/mint21.2-beta/assets/23406555/775cabdf-b2a8-464d-9871-ac33386b8c9b)

**Comment by clefebvre** [comment]
There's not enough info here to see a bug... it's not going to be installed.. why?

apt install mint-common

**Comment by mtwebster** [comment]
This is an issue with 'critical' packages - selecting one immediately simulates uninstalling it, which causes a dependency failure like this. We hardcode some packages that should be marked 'critical' but aren't.
https://github.com/linuxmint/mintcommon/blob/master/usr/lib/python3/dist-packages/mintcommon/installer/_apt.py#L21-L23
