### ISSUE TITLE
Add styles for Yaru-icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21.2-beta#44]
Just a suggestion, add the Mnt-Y theme style with Yaru icons. Write down the possible combinations:
  Mint-Y: Yaru-olive, Yaru-viridian, Yaru-sage.
  Mint-Y-Aqua: Yaru-blue.
  Mint-Y-Blue: Yaru-blue.
  Mint-Y-Grey: Yaru-blue.
  Mint-Y-Orange: Yaru.
  Mint-Y-Pink: Yaru-Magenta.
  Mint-Y-Purple: Yaru-purple.
  Mint-Y-Red: Yaru-red.
  Mint-Y-Sand: Yaru-bark.
  Mint-Y-Teal: Yaru-prussiangreen.

**Comment by clefebvre** [comment]
Thanks for the suggestion.

A Yaru style would be better represented with corresponding Yaru themes. We don't ship with these however.
