### ISSUE TITLE
Close button in applications

### ISSUE THREAD

**Issue by ParsaJR** [linuxmint/mint21.2-beta#45]
When the mouse pointer reaches the most possible corner on the right side, it should always be on the close button (to close the program by clicking, but this does not happen). I realized that this problem is only in Firefox. This happens when we turn off the title bar from Firefox. 

![Screenshot from 2023-06-26 10-04-05](https://github.com/linuxmint/mint21.2-beta/assets/98831377/a98535ea-cdca-4672-9a7f-5590af6d9fa2)
![Screenshot from 2023-06-26 10-32-51](https://github.com/linuxmint/mint21.2-beta/assets/98831377/9e5316bf-8969-402a-bfb4-49603bd129df)

**Comment by clefebvre** [comment]
This should be reported to Mozilla directly. We ship with the titlebar ON by default. Turning it OFF creates all sorts of issues.
