### ISSUE TITLE
Add style for yaru theme

### ISSUE THREAD

**Issue by mdevansh06** [linuxmint/mint21.2-beta#46]
add a cinnamon style for yaru theme like there are styles for mint-y and mint-x which use corresponding yaru gtk theme, sound theme, icon theme and cursor .

**Comment by kacperpaczos** [comment]
What do you mean? Could you please explain more?

**Comment by mdevansh06** [comment]
just like there is a cinnamon style for mint-y and mint-x themes in the simplified  theme settings, there should be a style for yaru themes.
choose yaru from the list, choose an accent color and the yaru cursor and sound theme get applied automatically, just as this happens for mint-y

**Comment by kacperpaczos** [comment]
Ok, but I can't see any Yaru themes. I can only see Yaru icons. Probably the LM doesn't have this theme installed by default, so it's a feature request, not a bug.

Do you use Yaru (the official Ubuntu theme) on your system? Can you show me some screenshots?

**Comment by mdevansh06** [comment]
I do not remember if i installed yaru myself or it was preinstalled.
You can see  yaru on action in ubuntu cinnamon website.
Yaru cinnamon theme is available to download from packages.ubuntu.com , not available in 22.04 lts.

**Comment by mdevansh06** [comment]
![cinnthem](https://github.com/linuxmint/mint21.2-beta/assets/120102208/70c50cf6-c202-4119-9b4b-7ea4d036d98a)
![cinnsett](https://github.com/linuxmint/mint21.2-beta/assets/120102208/adc78ef1-edb7-456f-a2d4-e41c92c0c658)
![cinnnemo](https://github.com/linuxmint/mint21.2-beta/assets/120102208/c606368c-4e61-4ed9-85a9-79468a3a3b50)
![cinnmenu](https://github.com/linuxmint/mint21.2-beta/assets/120102208/598963f6-97d4-4983-ab9a-6c4051ede2e1)
![cinndrop](https://github.com/linuxmint/mint21.2-beta/assets/120102208/a8003d04-f14a-4a17-9ca7-ae0898c82a28)

here are the screenshots of my desktop with yaru-cinnamon

**Comment by clefebvre** [comment]
Hi,

We don't ship with Yaru themes. It's a good idea to create a cinnamon style for them, but this should be done upstream by the Yaru team.
