### ISSUE TITLE
Nemo sorting upper case file/folder names before lower case

### ISSUE THREAD

**Issue by fredcw** [linuxmint/mint21.2-beta#47]
Nemo file and folder sorting by name has become case sensitive (including desktop)

**Comment by mtwebster** [comment]
It seems ok to me:
![image](https://github.com/linuxmint/mint21.2-beta/assets/262776/e08fb0ea-0915-406b-968a-c59d8bb32be7)

Make sure you don't have any sort of locale/region issues.

**Comment by fredcw** [comment]
That's odd. I'm running the linuxmint-21.2-cinnamon-64bit-beta.iso in Boxes vm.

![Screenshot from 2023-06-26 19-52-45](https://github.com/linuxmint/mint21.2-beta/assets/58893963/dc822f67-0e33-4c20-89ca-e6572dba6c06)

I didn't change any settings, just opened nemo.

**Comment by mtwebster** [comment]
I can get this to happen if I run:
```
LANG=C LANGUAGE=C nemo
```

What is the output of `locale`?

**Comment by fredcw** [comment]
Yes, it's LANG=C.UTF-8

I guess it's because no language or region is set until it is installed. Sorry, didn't think of that.
