### ISSUE TITLE
cinnamon: window tiling issues with some apps

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#48]
The window tiling function has changed in some apps compared to LM21.1.

Software Manager does not allow to tilt the window sideways [the same happens with Pix.]: 

[side-tiling.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/330a654a-dfa0-4249-925b-5769b7e0cacd)

LM.21.1: 

[21.1.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/fcde2f41-1ae7-458b-bb54-f9900a109d83)

 Update Manager, Xviewer and Bulky do not allow to tilt the window up or down.

**Comment by mtwebster** [comment]
There's nothing wrong with tiling, it's just that the minimum size of these windows will not allow them to be tiled in certain positions.

For example, if you open Bulky, shrink it vertically as far as it will go, its height is 418.  If your monitor has less vertical resolution than 2 * 418 (836), tiling to the top or bottom (or upper corners) won't be possible.

On the other hand, its minimum width is 515, so as long as your monitor has more than 1030 horizontal pixels, it will tile left/right.

We don't set the minimum sizes usually - Gtk figures it out based on the layout of the application's gui - it knows how far this or that widget or scrolled area can shrink to.

This is a common issue on lower resolution displays (like on netbooks). The best we can do for some things is make sure windows' minimum sizes will fit comfortably in the work area.

**Comment by haggen88** [comment]
I understand, in truth I was only concerned about the change of windows tiling of the Software Manager.
