### ISSUE TITLE
cinnamon: Panel menu shows up behind the panel when Auto-hide is set

### ISSUE THREAD

**Issue by ChoquePumper** [linuxmint/mint21.2-beta#49]
It seems it only affects to the bottom panel.
You can bring the panel menu by right clicking on the panel and it should be above the panel. When Auto-hide panel is set, either **auto** or **intelligent**, every time the menu has to update its position it checks internally some "hint" telling whether the panel is hidden or not.

When the panel menu is showed up, the panel has to remain on screen until the menu closes. That's fine. If you move the cursor outside the panel area (to inteact with the menu) the "hint" is set to "hidden". Then if you click on something that opens a submenu, the panel menu will adjust it's position in order to show all the items on screen, but because the "hint" suggests that the panel is "hidden", the panel menu won't take account the current panel position (to be on screen) and the menu items at the bottom will be behind the panel making it impossible to click on them.

Video:

https://github.com/linuxmint/mint21.2-beta/assets/58898942/2eb04ed4-3acb-49b9-98b7-e2fa358262b6

If animations are enabled, you can change the "hint" value by moving the cursor back into the panel area right before the animation ends and the menu will be above the panel.

The issue is been there since the version 21 release.

**Comment by clefebvre** [comment]
Added to roadmap for the next dev cycle.
