### ISSUE TITLE
Flatpak programs bypass notification settings

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint21.2-beta#5]
Not exactly Mint 21.2 bug, but didn't know where to exactly report it before.

When you have a Flatpak program that uses notifications (for example Bottles when you create a new bottle) it doesn't respect your notification settings and it always shows in the taskbar even if you have them turned off.

To reproduce:
1. Turn off notifications in your Notifications settings
2. Use some Flatpak program that uses notifications and see the results

**Comment by clefebvre** [comment]
Notifications are visible on the screen (top-right corner of the screen). If you disable them they no longer show up.

What you see in the panel is the notification applet, it's there to show you notifications you missed, whether or not they're enabled. If you don't want that you can remove the applet.
