### ISSUE TITLE
Some Korean translations missing

### ISSUE THREAD

**Issue by hywol** [linuxmint/mint21.2-beta#50]
![image](https://github.com/linuxmint/mint21.2-beta/assets/72562677/6e6ec642-9f05-48af-bfa6-ceed822e4341)

![image](https://github.com/linuxmint/mint21.2-beta/assets/72562677/e25a01e7-382e-4b8d-8751-83794ff407cd)

Theme settings, Gesture settings translations missing.

**Comment by Fantu** [comment]
Hi, translations are made in Launchpad: https://translations.launchpad.net/linuxmint/latest/
anyone from this language can do the translations there and then they will be imported into the next version of cinnamon-translations
