### ISSUE TITLE
gnome-calendar: 'prefer dark mode' option causes event labels not to be readable

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#51]
[gnome-calendar-theme-dark.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/a52bbd1f-0235-4d8b-96e4-dd59a923cb83)

BTW: [similar issue](https://github.com/linuxmint/mint-themes/issues/331)  

**EDIT:** Probably #16 is related, as at the end of the video you can see that the dark theme changes to a different Mint one.

**Comment by JosephMcc** [comment]
This is just another symptom of the exact same issue. The theme switches to Adwaita-dark in the case you are showing at the end. The unreadable label isn't a Mint issue. However the fact that is switches to a different theme like that in the first place is an issue with mint-themes.

**Comment by mdevansh06** [comment]
#16

**Comment by haggen88** [comment]
@JosephMcc I confirm, the problem is with  Adwaita. In LM21.1 it also presents problems when choosing the theme of the application (also in 21.2):

![Adawaita LM21 1](https://github.com/linuxmint/mint21.2-beta/assets/68134588/d7f79336-8dfd-4f29-80cc-39fdd65e5887)

**Comment by haggen88** [comment]
BTW @JosephMcc ,there are also issues with the Mint-Y-Dark variants in LM 21.2 & [21.1](https://github.com/linuxmint/mint-l-theme/issues/9)

![Mint-L-Dark](https://github.com/linuxmint/mint21.2-beta/assets/68134588/4c6a6364-8685-4405-a321-1f78ab5f568d)
