### ISSUE TITLE
muffin: decoration icons come from icon theme instead of gtk theme

### ISSUE THREAD

**Issue by biki28** [linuxmint/mint21.2-beta#55]
Window control buttons are inconsistent with some icon themes which are installed by default namely numix, papirus. This issue is from mint 21.
here is the reference of the same issue in mint 21.1 beta 
https://github.com/linuxmint/mint21.1-beta/issues/78

**Comment by SebastJava** [comment]
@johnsonmt01 had previously suggested a possible solution to this on my Mint-Yz-theme fork from Mint-Y:

> I've noticed that with mint-y-legacy, and the older mint-yz themes based on them, the window controls are consistent across Metacity/GTK, regardless of icon theme. This appears to be caused by a reference in gtk.css to an "assets" folder stored alongside gtk.css, which stores the window control icons. This reference drives the consistency.
> 
> Presumably, it would be possible in current mint-yz themes to remove the gtk.css reference and dependency on Mint-Y icons, and replace that with an "assets" folder ensuring consistent window controls. Unless users prefer the variety, of course.

ref: https://github.com/SebastJava/mint-yz-theme/issues/55#issue-1574485369

Sorry, i still haven't tried this, i haven't done anything in that repository since Oct 12, 2022.

**Comment by johnsonmt01** [comment]
This may be of interest; I did some work recently related to modifying window controls.
https://forums.linuxmint.com/viewtopic.php?t=398557

**Comment by clefebvre** [comment]
Re-added to roadmap for 21.3.
