### ISSUE TITLE
mintmenu: Reordering the programs listed in the menu editor is not reflected in the main menu.

### ISSUE THREAD

**Issue by adrianlopezgalera** [linuxmint/mint21.2-beta#56]
Hi everyone,

I have noticed that in version 21.2 there is still a bug that was already in 21.1. Mate's menu editor allows programs to be reordered using an "up" and "down" button. However, altering the position of the programs has no effect. In other distributions with Mate, this function does work.

Unfortunately, I think the menu editor is one of the most outdated components in Linux Mint. It doesn't seem to be up to the quality of other components and needs a lot more attention. I consider it essential that the three desktops, or at least Cinnamon, had an easy way to customize the order of listed programs. It would suffice if there were, as in Mate, an "up" or "down" button and that these changes be reflected in the main menu.

After installing many programs, it becomes so cluttered that it makes using the main menu very cumbersome. There is no way that an ordinary user can put in the first places of each category those programs that he/she uses most frequently.

I think this feature is easy (compared to others) to solve and very essential.

Regards.

**Comment by clefebvre** [comment]
I don't think mintmenu ever supported reordering. What you're looking at in the menu editor is a separate project called mozo.

I've added an item planned for 21.3 in our roadmap to either bring support for reordering in mintmenu or adapt mozo to it.
