### ISSUE TITLE
Monitor (Displays) preferences icons lagging

### ISSUE THREAD

**Issue by la4gia** [linuxmint/mint21.2-beta#57]
The monitor icons drag when moving in xfce. 

Steps to reproduce:
    1. Plug in a second monitor
    2. Open Displays app (monitor preferences)
    3.  Grab the pink or green icon and move it

![image](https://github.com/linuxmint/mint21.2-beta/assets/105323071/f50e5333-2ac9-4853-8e60-d24f230dd011)

**Comment by clefebvre** [comment]
Please report this bug directly upstream to Xfce.

https://bugzilla.xfce.org/
