### ISSUE TITLE
cinnamon: Sometimes the applet menu opens taller than its saved popup size

### ISSUE THREAD

**Issue by axel358** [linuxmint/mint21.2-beta#6]
https://github.com/linuxmint/mint21.2-beta/assets/72220889/4b01d75b-23cb-4118-9c8c-05ff03de114b

See how the saved menu size its supposed to reveal only up to the Web category, but after a few opens it grows taller and the Wine category becomes visisble

**Comment by clefebvre** [comment]
@mtwebster is working on a fix for this afaik
