### ISSUE TITLE
21.2 XFCE problem installing OpenVPN3

### ISSUE THREAD

**Issue by peter0548** [linuxmint/mint21.2-beta#60]
Attempted install of OpenVPN3 on 21.2 XFCE beta - preliminary setup all appeared to complete. Final step - actual install failed with two files listed as not installable:
openvpn3 : Depends: libjsoncpp25 (>= 1.9.5) but it is not installable
                   Depends: libtinyxml2-9 (>= 8.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
I have multiple machines running Mint 21.1 XFCE and OpenVPN3 (installed by same process as used here) 
Process listed at:
https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux
peter

**Comment by clefebvre** [comment]
Hi @peter0548,

This look like either a repository misconfiguration or a package conflict with a 3rd party repository.

Please use the forums, IRC or Discord to find help and troubleshoot this issue.

Don't hesitate to add information about your repositories (output of "inxi -r").
