### ISSUE TITLE
Mint-L: style should use the DMZ-White

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/mint21.2-beta#61]
It's supposed to look like 20.2.

Additionally, users switching from Windows will probably want a more traditional cursor.

**Comment by clefebvre** [comment]
It's subjective and I understand your reasoning. That said, the choice of icon cursor isn't as simple as a GTK theme, this is also set in the login screen and other parts of the OS. I'd rather keep it simple and working OOTB as much as possible.

**Comment by Secret-chest** [comment]
Also, I've seen many reports of users trying to find the cursor theme in the mouse settings.
