### ISSUE TITLE
cinnamon: Low battery notification priority in fullscreen apps

### ISSUE THREAD

**Issue by thiagonebuloni** [linuxmint/mint21.2-beta#62]
Linux Mint 21.1 Vera
Cinnamon 5.6.8

Whenever the battery power is critic it shows a notification on the screen. When watching videos in fullscreen mode this notification doesn't appear and the machine just power off. Maybe it just doesn't have the right priority to show up in front of an app in fullscreen.

It happens with Google Chrome and VLC Media Player

**Comment by clefebvre** [comment]
We'll add a new setting in the next version of Cinnamon to control whether notifications should or shouldn't show up on top of fullscreen windows.

Added to 21.3 roadmap.
