### ISSUE TITLE
mint-themes: Sliders are too small in 2.1.4

### ISSUE THREAD

**Issue by axel358** [linuxmint/mint21.2-beta#63]
![Screenshot from 2023-07-01 15-22-35](https://github.com/linuxmint/mint21.2-beta/assets/72220889/dbb36af5-11f3-4c97-9973-83a98e1e5f19)

Same for the sound applet when no media is playing

**Comment by axel358** [comment]
![sound](https://github.com/linuxmint/mint21.2-beta/assets/72220889/af0cc665-9fb8-4834-8ea8-964d743fea01)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mint-themes/commit/30e0795ae76b97d12bd7c41495871179d99b299b
