### ISSUE TITLE
Gparted: Icons difficult to see

### ISSUE THREAD

**Issue by callagg2** [linuxmint/mint21.2-beta#64]
In this new beta version of Linux Mint, the icons to "Apply all Operations" and "Undo" blend into the background. 
They are difficult to read.
This was the standard theme, i didn't touch it since installing the beta version.
![Gparted_icons](https://github.com/linuxmint/mint21.2-beta/assets/15323690/0134be8a-c51f-4685-9166-72ca960a7aca)

**Comment by billyswong** [comment]
This is definitely NOT the standard theme. Are you installing as upgrade and inherited personal configuration from the past? I can recognize the icon set is from Mint-X. Mint-X is incompatible with dark mode.

**Comment by callagg2** [comment]
Yes, i don't remember ever changing the themes. 
I doubt that because i'm dual booting with LMDE and my home folder being on a separate partition had a bearing, but you're definitely correct, the icons were Mint-X. I changed them to Mint-Y and they appear fine now. 

![image](https://github.com/linuxmint/mint21.2-beta/assets/15323690/6b346397-95f3-4ec9-93f5-178afb810cc9)
