### ISSUE TITLE
Mint-L: incorrect text color for events in gnome-calendar when using dark mode

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#65]
![Screenshot from 2023-07-01 20-31-10](https://github.com/linuxmint/mint21.2-beta/assets/68134588/ea55ca3d-d91a-48d1-b537-19514672f566)

updated to:
- Cinnamon 5.8.3
- mint-themes 2.1.4
- mint-l-theme 1.9.4

Ref: [same bug](https://github.com/linuxmint/mint-themes/issues/331)

**Comment by anaximeno** [comment]
This is happening with the current Mint-Y theme as well.

**Comment by haggen88** [comment]
With Mint-Y in 21.2 beta I had no problems. With Mint-X when selecting 'prefer dark mode' something similar happens {apparently loads Adwaita's theme}.

![mint-x](https://github.com/linuxmint/mint21.2-beta/assets/68134588/2362f673-51f4-4611-9531-c14d816cf702)

**Comment by anaximeno** [comment]
> With Mint-Y in 21.2 beta I had no problems. 

That's strange, see mine (Mint-Y-Dark-Blue):

![Screenshot from 2023-07-02 15-10-42](https://github.com/linuxmint/mint21.2-beta/assets/63073056/de514ecf-6de8-4da2-9b5d-0721d6bd4ca2)

### Version
- mint-themes 2.1.4
- Cinnamon 5.8.3

**Comment by haggen88** [comment]
mmm... interesting; I have also noticed that sometimes when changing the application theme it is necessary to restart gnome-calendar so that the correct theme is applied.
