### ISSUE TITLE
gnome-screenshot: few problematic behaviors

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint21.2-beta#69]
I wanted to make a regional screenshot of Steam and noticed that one window is out of place.
Use the shortcut Shift+PrntScr when you have notifications window opened (that one with bell icon next to your username).
That window is not colored like the rest of the screen and you can't move your mouse there when selecting the region (you need to circle it behind)
note: using Steam Flatpak

Also while I'm at it some apps don't allow you to make a screenshot in any way (neither regional or whole screen) when some menu is opened. You can see it for example in Flatseal - open the program, click on 3 line hamburger menu and try to make a screenshot.

**Comment by mtwebster** [comment]
The steam issue is something on their end, I have a feeling they're deliberately not compositing the notification window so it'll be able to show above fullscreen games. They really should only do this if a fullscreen game is actually running. We might be able to override it in our window manager but I don't think it's worth the potential for regressions elsewhere. They should just fix it.

The second issue is an inherent behavior in X11 - only one window can have exclusive focus at a time, and popups like right-click menus (any Gtk app right-click menu, like those in nemo or xed, etc...) by nature take focus so they can be navigated using a keyboard. Shortcut keys like printscreen become disabled when in this state.

That behavior can also prevent things like the screensaver from starting (resulting in hacky workarounds like linuxmint/cinnamon-screensaver@4ae9f1da8aed493d1d1f02b43fcb51803573042d to close this potential security hole).

A couple other discussions about it:
https://bugzilla.gnome.org/show_bug.cgi?id=440515
https://github.com/linuxmint/cinnamon-screensaver/issues/93
There's plenty more out there.
