### ISSUE TITLE
cinnamon: virtual keyboard display minimized

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#7]
![v1](https://github.com/linuxmint/mint21.2-beta/assets/68134588/beb93941-cd38-4eb6-bdd5-ff0567000314)
![v2](https://github.com/linuxmint/mint21.2-beta/assets/68134588/37b18a69-cb1b-457f-b63b-135840acaa6c)

Unlike Mint 21.1, it only occupies a small portion of screen. LM 21.1:

![21 1](https://github.com/linuxmint/mint21.2-beta/assets/68134588/3d08d9a7-f281-4ed5-a09e-ffaae7238bb9)

The keyboard does not change size  when changing the configuration [System settings / accessibility].

[Kazam_screencast_2023-06-21_02-45-02.webm](https://github.com/linuxmint/mint21.2-beta/assets/68134588/2bf7430c-2032-44ce-b392-5fc368adbbc0)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/9b4bc847385e8c56ba227e81e34e9407edf40032

..messed up the Fixes link
