### ISSUE TITLE
[mate] mate-tweak not working

### ISSUE THREAD

**Issue by falket** [linuxmint/mint21.2-beta#71]
I used to use mate-tweak to "revert" to something similar to the old gnome2 look or to something similar to other oses. With ubuntu mate 22.04 , mate-tweak works. 

With mint 21.2 beta it doesn't, and it's far from easy to have a two panel layout similar to gnome 2 (i have tried adding a 2nd panel, but after all i still don't have the "windows key" shortcut for the old style menu, and i'm unable to move network volume and so on on the upper panel).

If i choose to change theme, nothing happens.

Here is the console output:

Window Manager is: marco
System installed layouts: 
['fedora', 'default', 'linuxmint', 'opensuse']
Current layout: mint
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "buttons" argument must be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:690: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(text)
Switching to: default
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1047, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1031, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 768, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 571, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid
  File "/usr/lib/python3.10/subprocess.py", line 969, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-applet'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mate-tweak.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1047, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1031, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 768, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 571, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid
  File "/usr/lib/python3.10/subprocess.py", line 969, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-applet'

Thank you in advance.

**Comment by mtwebster** [comment]
It looks like mate-tweak is broken - mate-volume-control-applet is in /usr/libexec which isn't in the path. It probably works in Ubuntu because the code here is conditional on something else that is true in ubuntu but not mint.

run:
```
PATH=$PATH:/usr/libexec mate-tweak
```
and try it, it should work.

**Comment by falket** [comment]
Thank you this way it works!
