### ISSUE TITLE
[Visual tweaks/opinion] Cinammon thoughts on simplified theme selector, cursor and new hover states

### ISSUE THREAD

**Issue by wisnie** [linuxmint/mint21.2-beta#72]
Hello,

I have been a happy user of `20.3` for almost a year now, so I experienced a couple of changes (some of which may be dated back to other releases) in the new release. What I find **inconsistent** are the following things:

1. By using simplified theme selector, e.g. by selecting white it does not automatically update (Settings > Miscellaneous options > Dark mode > Prefer light mode), which probably should happen. I am not sure myself how this setting even work (I'll develop on this in next item).
2. Gnome terminal by default has the `Use colors from system theme` option checked, but even when I manually select (Settings > Miscellaneous options > Dark mode > Prefer light mode), the background of shell still has dark background.
3. Only recently I have found out that there are `Login Window` settings, which enable you to choose cursor in that phase. Up to that point I thought that it was inevitable inconsistent bug between login window and desktop environment. I personally think that by selecting cursor in theme selector it should be automatically updated in login window.
4. I find new hover states (Mint-Y) really annoying, to the point I am willing to use Mint-X. Thinking in design terms it looks rather cheap, it reminds me of creating first web pages with the use of vibrant colors. Using the default yellow box, black text hover would have more contrast, be consistent with browser (Firefox) behavior.

Overall I like using Mint as my daily driver.
Thanks for your work.

**Comment by zsolaj** [comment]
Regarding point 3, if there are several user accounts with different cursors set, which user's preference should the login screen default to in your opinion?
As inconvenient as it is on a single-user machine, I do believe this is the correct way of handling this. I don't know how often people switch cursors, but I usually do it once, right after a fresh install, and then forget about it. It's not a big deal in my opinion having to set it that one time in the login window settings, too.

**Comment by wisnie** [comment]
I get your point, but as you mentioned it can be confusing on a single user machine.

None of my points are of urgent nature, it's more of stylistic choice.

**Comment by Qronikarz** [comment]
> 1. By using simplified theme selector, e.g. by selecting white it does not automatically update (Settings > Miscellaneous options > Dark mode > Prefer light mode), which probably should happen.

This was already reported few times during this beta and I believe it will be reported more since there is some reason that the developers don't want to (or even can't) do it this way.

> 3\. I personally think that by selecting cursor in theme selector it should be automatically updated in login window.

This probably is due to the same reason as above though I wish the default wasn't Bibata since I quite don't like this cursor and it's the thing I need to constantly change if I use the simplified themes window to change accent colors.

**Comment by clefebvre** [comment]
The login window doesn't belong to the user. It needs admin privileges and applies to the entire box. Gnome terminal is an upstream app.. same for Celluloid. We can patch them to a point but the design belongs to upstream.
