### ISSUE TITLE
ubiquity: User Account page uses fullcolor icons

### ISSUE THREAD

**Issue by pilatomic** [linuxmint/mint21.2-beta#73]
When compared to Mint 21.1, the icon showing an accepted value for User name / password is different. 
Is this expected ? 
Left : Mint 21.1 Cinnamon
Right : Mint 21.2 Cinnamon Beta

![image](https://github.com/linuxmint/mint21.2-beta/assets/6799093/c46ab551-b58f-4e62-8206-8af5d1a3ee66)

**Comment by anaximeno** [comment]
> Is this expected ?

This seems to be a consequence of what they said in the section **Mono Icons** of the what's new page https://www.linuxmint.com/rel_victoria_cinnamon_whatsnew.php

**Comment by mtwebster** [comment]
Fixed: https://github.com/linuxmint/ubiquity/commit/8e2bd8403e0223fc03885ebb875066c33af248a2
