### ISSUE TITLE
Software Manager will Not maximise when screen resolution is 800*600

### ISSUE THREAD

**Issue by pilatomic** [linuxmint/mint21.2-beta#74]
On Linux Mint 21.2 Cinnamon Beta, with screen resolution set to 800x600px, pressing the "Maximise" button on the Software Manager windows produces no action, while it works as expected with screen resolution set to 1024x768px.

![image](https://github.com/linuxmint/mint21.2-beta/assets/6799093/def33b9e-c00f-405e-abd9-35bcaf71ad16)

This works correctly on Mint 21.1 Cinnamon

**Comment by JosephMcc** [comment]
My guess here is that the minimum width of the window is over 600px so it can't be resized narrow enough to maximize. It's different in 21.2 because there was a bit of redesign done.

**Comment by clefebvre** [comment]
1024x768 is the lowest supported resolution.

**Comment by billyswong** [comment]
@clefebvre 
Slightly offtopic but will Linux Mint also maintain support of 1280x720? It is the effective resolution of 1920x1080 laptop screen running 150% scale. Many of those screens requires 150% scale to regain a closer match of 96dpi. I think it is a common enough hardware config that deserves some degree of support.
