### ISSUE TITLE
cinnamon: network applet, list of networks is way too large

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#9]
After a while connected to wifi the "more" section appears empty, and the list of networks is displayed too big for the screen [1366x768] , exceeding the limits in which you can navigate.

![n0](https://github.com/linuxmint/mint21.2-beta/assets/68134588/3589e05e-8bb6-43a3-9ebd-6cae645d55d5)
it is also noted that the list is not sorted by wifi signal strength [%], and sometimes the 'More' option appears in the middle of the list, or that the signal of the connected wifi network shows it as 0%.

![mid](https://github.com/linuxmint/mint21.2-beta/assets/68134588/09f3e9c9-8bb3-4299-b491-daa4fc39f41d)

![lm_21 2](https://github.com/linuxmint/mint21.2-beta/assets/68134588/650a73e0-190f-4654-b32e-7874eb44ce93)

Nornal:
![normal](https://github.com/linuxmint/mint21.2-beta/assets/68134588/87ef38a5-cea3-4a37-9fa6-37a28b0d9441)

I thought the problem was because I had installed a wifi usb adapter, but the problem happens with or without it connected.

It also happens in Cinnamon 5.6. 

![lm21 1](https://github.com/linuxmint/mint21.2-beta/assets/68134588/76883c33-6842-4c52-9d08-ae98afdaf347)

Reviewing it is a problem that is dragging since at least 2016!!: https://github.com/linuxmint/cinnamon/issues/5660

**edit:** The more often you click on the applet, the more likely you are to see the bug.

**Comment by clefebvre** [comment]
This requires some refactoring and it's not a new issue. We'll tackle in the next dev cycle. Added to roadmap.
